DYNAMODB_TABLE: DYNAMO-TABLE
DYNAMODB_REGION: us-east-1

REDIS_PORT: 6379
REDIS_HOST: REDIS-HOST
REDIS_TTL_SECONDS: 3600

SUBNET1: SUBNET1-ID
SUBNET2: SUBNET2-ID
SUBNET3: SUBNET3-ID
SECURITY_GROUP: SECURITYGROUP-ID

SHORTENER_DOMAIN: https://app-base-domain.com