DYNAMODB_TABLE: shortener-url
DYNAMODB_REGION: us-east-1
DYNAMODB_TABLE_PARTITION_HASH: $6Q*WAc93ygt
SHORTENER_DOMAIN: https://dwuxe0ioie.execute-api.us-east-1.amazonaws.com
REDIS_PORT: 6379
REDIS_HOST: shortener-cache.qlsuyf.clustercfg.use1.cache.amazonaws.com
REDIS_TTL_SECONDS: 3600
SUBNET1: subnet-2035c47d
SUBNET2: subnet-0be4736f
SUBNET3: subnet-2232ce0d
SECURITY_GROUP: sg-4ac9f338